### ISSUE TITLE
Incorrect duplicate path parameters detected

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#100]
From the OpenAPI spec:

> A list of parameters that are applicable for this operation. If a parameter is already defined at the Path Item, the new definition will override it but can never remove it. The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. The list can use the Reference Object to link to parameters that are defined at the OpenAPI Object's components/parameters.
--

It says: "The list MUST NOT include duplicated parameters."  

However, right before that it says: "If a parameter is already defined at the Path Item, the new definition will override it but can never remove it."

So I gather something like this should be okay:

```yaml
parameters:
  - name: adam
     in: path
     required: true
     description: Version A description
     schema:
       type: string

post:
  operationId: myExample
  parameters:
    - name: adam
       in: path
       required: true
       description: Version B description
       schema:
         type: string
# etc....
get:
# etc...
```
