### ISSUE TITLE
Bad validation for examples

### ISSUE THREAD

**Issue by bifot** [Redocly/openapi-cli#139]
I'm creating examples as shown [here](https://swagger.io/docs/specification/adding-examples/).

```yml
components:
  ...
  examples:
    Markets:
      usd:
        eur: true
        btc: true
        xrp: true
        ltc: true
      btc:
        usd: true
        eur: true
        xrp: true
        ltc: true
  ...
```

Then I'm running `npx @redocly/openapi-cli validate spec.yml` and got error:

![image](https://user-images.githubusercontent.com/5220114/83140598-ff122680-a0f6-11ea-8a78-f814fb6ad2d9.png)

**Comment by RomanHotsiy** [comment]
This is a valid error.

`examples` is a Map from example name to [Example Object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#exampleObject). Example object has top-lever props and you are supposed to add your example under `value`:

```yaml
components:
  ...
  examples:
    Markets:
      value:
        usd:
          eur: true
          btc: true
          xrp: true
          ltc: true
        btc:
          usd: true
          eur: true
          xrp: true
          ltc: true
  ...
```
