### ISSUE TITLE
Bundle doesn't support OpenAPI yaml with $ref's

### ISSUE THREAD

**Issue by vpmv** [Redocly/openapi-cli#184]
**Describe the bug**
Trying to run `openapi bundle -o openapi.json openapi.yaml` returns a heap of `cannot resolve $ref` errors. <br>
Running `openapi preview-docs` works fine though.

**To Reproduce**
Create any  YAML file with component refs (like schemas or routes) and try to bundle it.

**Expected behavior**
A bundled file

**Logs**
Exerpt:
```
[100] openapi.yaml:177:7 at #/components/schemas/Foo

Can't resolve $ref: ENOENT: no such file or directory, open '/home/user/MYPROJECT/docs/components/responses/components/schemas/foo.yaml'

175 |   $ref: "./components/schemas/object.yaml"
176 | Foo:
177 |   $ref: "./components/schemas/foo.yaml"
178 | Bar:
179 |   $ref: "./components/schemas/bar.yaml"

Error was generated by the bundler rule.
< ... 22 more problems hidden > increase with `--max-problems N`
```

**OpenAPI definition**
not possible

**Version(s)**
1.0.0-beta.8

**Additional context**
I'm looking for an easy way to run a yaml to json bundling through docker.

**Comment by RomanHotsiy** [comment]
> Can't resolve $ref: ENOENT: no such file or directory, open '/home/user/MYPROJECT/docs/components/responses/components/schemas/foo.yaml'

But do these files exist in fact? Can you verify that?

**Comment by adamaltman** [comment]
I'm not able to reproduce this one. Maybe @vpmv can supply a zipped bundle of files with the reproduction?

**Comment by deniszgonjanin** [comment]
I'm seeing this as well. Seems to happen when `openapi-cli` is asked to follow more than one level of indirection. Here's a simple example that should reproduce:

Directory structure:
```
.
├── openapi.yaml
└── schemas
    ├── TypeA.yaml
    └── TypeB.yaml
```

openapi.yaml:
```yaml
openapi: "3.0.1"
info:
  title: Open API
  description: Open API
  version: v0
  contact:
    email: some@body.com
components:
  schemas:
    TypeA:
      $ref: ./schemas/TypeA.yaml
    TypeB:
      $ref: ./schemas/TypeB.yaml
```

TypeA.yaml:
```yaml
allOf:
  - type: object
    required:
      - name
      - integration_type
    properties:
      integration_type:
        $ref: "../openapi.yaml#/components/schemas/TypeB"
      name:
        type: string
```

TypeB.yaml:
```yaml
type: string
enum:
  - webhook
  - api_key
  - sftp
  - netsuite
```
