### ISSUE TITLE
bgColor is not a function when using invalid severity value

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#190]
**Describe the bug**

When running `openapi lint main`, I get this error. when I have an invalid severity value:

```
TypeError: bgColor is not a function
    at formatCodeframe (/Users/adam/Projects/Redocly/openapi-demo/node_modules/@redocly/openapi-cli/lib/format/format.js:87:33)
    at Object.formatProblems (/Users/adam/Projects/Redocly/openapi-demo/node_modules/@redocly/openapi-cli/lib/format/format.js:41:41)
    at /Users/adam/Projects/Redocly/openapi-demo/node_modules/@redocly/openapi-cli/lib/cli.js:105:26
    at Generator.next (<anonymous>)
    at fulfilled (/Users/adam/Projects/Redocly/openapi-demo/node_modules/@redocly/openapi-cli/lib/cli.js:6:58)
```

**To Reproduce**
1. Given this `.redocly.yaml` file (see snippet below) that has "warning" instead of "warn"
2. And running `openapi lint main`.
4. See error pasted above.

The same happens with any unexpected value for `severity` such as `foo`.

**Expected behavior**
A more friendly error message, such as "Invalid severity level; accepted values: `error` or `warn`".

**OpenAPI definition**
n/a

**Version(s)**
- 1.0.0-beta.9

**Additional context**

## `.redocly.yaml` file snippet
```
apiDefinitions:
  main: openapi/external.yaml
lint:
  extends:
    - recommended
  plugins:
    - './plugins/demo-plugin.js'
  rules:
    demo/response-contains-property: 
      severity: warning
```
