### ISSUE TITLE
Examples defined within the schema are not shown on redocly HTML document example section.

### ISSUE THREAD

**Issue by mh-spillai** [Redocly/openapi-cli#251]
**Describe the bug**
Examples defined within the schema are not shown on redocly HTML document example section.

**To Reproduce**
1. Generate HTML documentation corresponding to the following file.
   [sampleinventory.zip](https://github.com/Redocly/openapi-cli/files/6009253/sampleinventory.zip)
2. In the open API file, the "InventoryItem" schema has an example "example-1".
   
   ![image](https://user-images.githubusercontent.com/75423468/108493358-3ac7ce80-72cc-11eb-9945-dbc6d177e538.png)

    which is not showing in the generated HTML documentation.
   
    ![image](https://user-images.githubusercontent.com/75423468/108493583-7d89a680-72cc-11eb-8151-d5c362f3111b.png)

**Expected behavior**

 Examples declared within the schema should be shown on HTML file

**OpenAPI definition**
[sampleinventory.zip](https://github.com/Redocly/openapi-cli/files/6009253/sampleinventory.zip)
Version:-3.0.0

**`openapi-cli` Version(s)**
Latest version

**`Node.js` Version(s)**
12.0

**Comment by adamaltman** [comment]
@mh-spillai here is a snippet from your sample:

```
components:
  schemas:
    InventoryItem:
      type: object
      x-examples:
        example-1:
          id: d290f1ee-6c54-4b01-90e6-d701748f0851
          name: Widget Adapter
          releaseDate: '2016-08-29T09:12:33.001Z'
          manufacturer:
            name: ACME Corporation
            homePage: 'https://www.acme-corp.com'
            phone: 408-867-5309
```

You define `x-examples` ( https://redoc.ly/docs/api-reference-docs/vendor-extensions/redoc-supported-extensions/#x-examples ) which is a Redoc-invented vendor extension. The purpose was to support examples for swagger 2.0. Now, your definition is 3.0 and you've defined it on the schema instead of the media type object. You should define your examples with `x-` and put it on the media-type object. 

This response won't be good without an example: https://github.com/Redocly/openapi-starter/blob/main/openapi/paths/path-item-with-examples.yaml#L31-L39

```
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/Schema.yaml
        examples:
          mapName:
            summary: My first example
            description: My first example's description.
            value:
              stringProperty: tada
          mapNameDoesNotShowInDocsUnlessSummaryIsNotProvided:
            value:
              stringProperty: checkmark
```

I hope this is helpful.
