### ISSUE TITLE
String example fields are incorrectly converted to numbers during bundling when all characters are numeric with a leading zero

### ISSUE THREAD

**Issue by austpaul** [Redocly/openapi-cli#282]
**Describe the bug**
String example values with leading zeros are treated as numbers, with quotes being stripped during bundling, resulting in failing schema validation of the generated API definition file.

**To Reproduce**
1. Define a simple attribute example, or a complete example structure for (for request, response or in components/examples) having a quoted string attribute example value with numeric characters and a leading zero.
```
    Account:
      type: object
      description: Resource representing an account
      properties:
        id:
          type: string
          example: '0123456789'
  
    Customer:
      type: object
      description: Resource representing an account
      properties:
        id:
          type: string
          example: '1234567890' 
        name:
          type: string
          example: 'Contoso' 
```

2. Run openapi build

**Expected behavior**
These id string examples in `Account.id` and `Customer.id` must be kept after bundling. The non-numeric value in the `Customer.name` example can be stripped of the redundant quotes.
```
    Account:
      type: object
      description: Resource representing an account
      properties:
        id:
          type: string
          example: '0123456789'

    Customer:
      type: object
      description: Resource representing an account
      properties:
        id:
          type: string
          example: '1234567890' 
        name:
          type: string
          example: Contoso
```
**Actual behavior**
The example value in `Account.id` with a leading zero ends up without quotes, failing schema validation. The quotes are kept for the `Customer.id` example with a leading 1 digit. Quotes are stripped for the `Customer.name` example, as expected.
```
    Account:
      type: object
      description: Resource representing an account
      properties:
        id:
          type: string
          example: 0123456789
  
    Customer:
      type: object
      description: Resource representing an account
      properties:
        id:
          type: string
          example: '1234567890' 
        name:
          type: string
          example: Contoso
```

**OpenAPI definition**
3.0.1

**`openapi-cli` Version(s)**
1.0.0-beta.44

**`Node.js` Version(s)**
v15.10.0
