### ISSUE TITLE
bundler mishandling components:schemas with external reference

### ISSUE THREAD

**Issue by steve-nay-sage** [Redocly/openapi-cli#349]
**Describe the bug**
When bundling, a `$ref` to an external file in the `components:schemas` section produces a warning about two schemas with the same name, and bundler renames one of them. 

I thought that dereferencing external references like this is exactly what the bundle command is supposed to do, so I'm puzzled that it's messing this up. Or I'm not understanding something.

**To Reproduce**
1. Unzip the two attached files and then run the `openapi bundle` command on the `externalref.api.yaml` file.

That file is simplified to show this problem. It doesn't contain any paths. It just has a small components:schemas section that looks like this:

```
components:
  schemas:
    vendor:
      $ref: ./vendor.schema.yaml
```

That reference to an external file causes the bundler rule to warn that "Two schemas are referenced with the same name but different content." It bundles in the external schema as "vendor-2" and rewrites the vendor schema to be a $ref to vendor-2.

```
components:
  schemas:
    vendor:
      $ref: '#/components/schemas/vendor-2'
    vendor-2:
      title: vendor
      type: object
      description: Vendors
```

If that same external schema reference is in the paths section and there is no vendor in components:schemas, everything works fine. In other words, the bundler rule doesn't warn about an external schema reference in paths, but does warn about the same reference in schemas. 

**Expected behavior**
The bundler should happily bundle the external schema file into the original file to replace the $ref. Should look something like this:

```
components:
  schemas:
    vendor:
      title: vendor
      type: object
      description: Vendors
      properties:
        key:
          type: string
          description: System-assigned key for the vendor.
          readOnly: true
          ...
```

**OpenAPI definition**
OpenAPI v3.0

**`openapi-cli` Version(s)**
1.0.0-beta.54

**`Node.js` Version(s)**
v14.16.0

[external_ref_bug.zip](https://github.com/Redocly/openapi-cli/files/7061274/external_ref_bug.zip)
