### ISSUE TITLE
`path-excludes-pattern` built-in rule

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#394]
**Is your feature request related to a problem? Please describe.**

To prevent someone from making API paths like `GET /getAllCustomers` we can have a rule to prevent it.

**Describe the solution you'd like**

Basic usage:
```
lint:
  rules:
    path-excludes-pattern: error
```

The built in pattern list is the list of http methods:
- get
- options
- patch
- post
- put
- delete

Full list: https://webconcepts.info/concepts/http-method/ (We should not include the full list in our default rule.)

The rule should not be case-sensitive for people with paths that use casing. For example, `/PutMyCar` should match `put` and fail. False positives are to be expected... such as in a golf API `/putters`, and a movie API `/posters`, etc. That's okay and they can tweak these values in advanced usage and also use the ignore file to ignore specific false positives.

Advanced usage:

```
lint:
  rules:
    path-excludes-pattern:
       severity: error
       patterns:
           - ^.*get.*$
           - this could take regex I think? 
```

**Describe alternatives you've considered**

To allow regex or not? I think we should.

This may make writing the patterns a little more difficult`^.*get.*$` (and I had to spend 3 minutes on regex101 to figure that out).

**Additional context**

This is a common need so we should enable it as a built-in rule.

Having a solid base of built-in rules makes it easier to implement a full API design strategy faster.
