### ISSUE TITLE
`operation-description-override` built-in decorator

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#399]
**Is your feature request related to a problem? Please describe.**

See #397 and #398 

**Describe the solution you'd like**

```
lint:
  decorators:
    operation-description-override:
      PostCustomer: ./customer-operation-description.md
      PostOrder: ./order-operation-description.md
```
The decorator value is a map of operationId => path to Markdown file with description.

If the `operationId` does not exist, it has not impact.

If the API definition doesn't use operationId's... write your own decorator. 😄 

**Describe alternatives you've considered**

Inline Markdown.

**Additional context**

See #397 and #398
