### ISSUE TITLE
Incorrect behavior of resolve field in .redocly.yaml file

### ISSUE THREAD

**Issue by ofirm93** [Redocly/openapi-cli#412]
**Describe the bug**
In .redocly.yaml file the docs mention there is a field lint.resolve but in the implementation it is found in the the outer scope (lint is not resolve's parent but it's sibling). Either fix the docs to reflect that or fix the code to read it from the right place.

**To Reproduce**
Given this `.redocly.yaml` file resolve attribute is ignored.
```
apiDefinitions:
  # a set of named keys and values of entrypoints to OpenAPI definitions.
  # example
  public: .openapi.yaml

lint:
  extends:
    - recommended
  resolve:
    http:
      headers:
        - matches: https://github.com
          name: Authorization
          value: "Basic aaaa"
referenceDocs: {}
```
Given this `.redocly.yaml` file resolve attribute is used.
```
apiDefinitions:
  # a set of named keys and values of entrypoints to OpenAPI definitions.
  # example
  public: .openapi.yaml

lint:
  extends:
    - recommended
resolve:
  http:
    headers:
      - matches: https://github.com
        name: Authorization
        value: "Basic aaaa"
referenceDocs: {}
```

**Expected behavior**
The Authorization header should be added

**`openapi-cli` Version(s)**
1.0.0-beta.63

**`Node.js` Version(s)**
v16.12.0
