### ISSUE TITLE
New configurable rule: Allow us to disable warnings for unknown "format" values

### ISSUE THREAD

**Issue by mattholden** [Redocly/openapi-cli#482]
In our schema objects, we want to use the "format" field on properties for things like "ISO 3166-1 alpha-2" for Country Codes, "ISO 4217" for currency codes, and "E.164" for phone numbers, to specify to our users exactly how we expect fields that could be written multiple "valid" ways to be provided. The OAS specifically calls out that you may use formats not explicitly defined in the spec, but redocly throws a warning on it. We want to put in place policy that prevents deployment if there are any warnings, but we can't because these perfectly valid formats are throwing warnings.

Therefore, we'd love to see a configurable rule for "no-unknown-formats" or similar, with a default of "warn" to match current behavior, which we could then turn to "off" in our usage.

Thanks!

**Comment by adamaltman** [comment]
I am not able to reproduce this one. I don't get any warning when I try different formats. 

Can you clarify what version and command you are using? I tried version `1.0.0-beta.69` and `1.0.0-beta.76` (latest) and the `lint` and `bundle` commands.

I have an API I use for testing, and this is what I tried:

```
properties:
  id:
    readOnly: true
    type: string
    description: |
      WFD assigns a photo ID to each upload.
      Use the `photoId` as a filter to track ingredients added to the kitchen using the `ingredients-audit` API.
    format: uuid
```

And

```
properties:
  id:
    readOnly: true
    type: string
    description: |
      WFD assigns a photo ID to each upload.
      Use the `photoId` as a filter to track ingredients added to the kitchen using the `ingredients-audit` API.
    format: adam
```
And
```
properties:
  id:
    readOnly: true
    type: string
    description: |
      WFD assigns a photo ID to each upload.
      Use the `photoId` as a filter to track ingredients added to the kitchen using the `ingredients-audit` API.
    format: E.164
```

And
```
properties:
  id:
    readOnly: true
    type: string
    description: |
      WFD assigns a photo ID to each upload.
      Use the `photoId` as a filter to track ingredients added to the kitchen using the `ingredients-audit` API.
    format: ISO 4217
```
And

```
properties:
  id:
    readOnly: true
    type: string
    description: |
      WFD assigns a photo ID to each upload.
      Use the `photoId` as a filter to track ingredients added to the kitchen using the `ingredients-audit` API.
    format: ISO 3166-1 alpha-2
```

No warnings.

With this `.redocly.yaml`:

```
lint:
  extends:
    - recommended
```

(I also tried enabling all of the rules too.)

```
lint:
  extends:
    - all
  rules:
    request-mime-type:
      allowedValues: 
        - application/json
```
No relevant errors or warnings.
