### ISSUE TITLE
--remove-unused-components strips remotely referenced components

### ISSUE THREAD

**Issue by bojanz** [Redocly/openapi-cli#504]
I am currently testing --remove-unused-components with a spec that has $refs pointing to an external specification:
```
          properties:
            items:
              type: array
              items:
                $ref: 'https://my-other-api.my-service.io/openapi.yaml#/components/schemas/Order'
```

If I run openapi bundle, I can produce a dereferenced version:
```
openapi bundle -o openapi.combined.yaml --ext yaml openapi.yaml
```
This gives me a file with an Order schema included. However, if I add --remove-unused-components:
```
openapi bundle --remove-unused-components -o openapi.combined.yaml --ext yaml openapi.yaml
```
Then the Order schema gets immediately removed, because it's not detected as used.
