### ISSUE TITLE
[Help] `openapi lint` gives [WARNING] Unused rules found in config

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/openapi-cli#511]
**Describe the bug**
I'm receiving a `warning` message that some of my rules are not evaluated by the `lint` command.

**To Reproduce**
1. Given this `.redocly.yaml` file
2. And any OpenAPI file(s)
3. Run this command with these arguments... `openapi lint <spec> --format=stylish --config=<path>`

**Expected behavior**
All configured rules including `extends` and `custom rules` will be evaluated.

I did not find any information about `plugin prefix` or how to use it. I've not used it before and the cli was working as expected.

**Logs**
Woohoo! Your OpenAPI definition is valid. 🎉

[WARNING] Unused rules found in ../.redocly.yaml: path-characters
Check the spelling and verify you added plugin prefix.

**OpenAPI definition**

OAS3.0.3

```yaml
lint:
  extends: [recommended]
  rules:
    info-license: off
    info-license-url: off
    operation-tag-defined: off
    tag-description: off
    no-unused-components: off
    no-empty-servers: off
    # DO limit your URLs characters to 0-9 A-Z a-z - . _ ~ :
    path-characters:
      description: Path should contain only recommended characters.
      message: Path contains non-recommended characters.
      severity: info
      formats: ['oas2', 'oas3']
      given: $.paths.*~
      then:
        function: pattern
        functionOptions:
          # Check each path segment individually and ignore param segments
          # Note: the ':' is only allowed in the final path segment
          match: '^(/([0-9A-Za-z._~-]+|{[^}]+}))*(/([0-9A-Za-z._~:-]+|{[^}]*}(:[0-9A-Za-z._~-]+)?))$'
```

**`openapi-cli` Version(s)**
$ openapi --version && node --version
1.0.0-beta.79
v12.22.7

**Additional context**
