### ISSUE TITLE
[plugins] `mustExist` for custom rules does not give an error for additional properties

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/openapi-cli#514]
**Is your feature request related to a problem? Please describe.**
following the example for [Plugins](https://redoc.ly/docs/cli/guides/response-contains-property/#response-contains-property-custom-rule)

I successfully created an example to test required properties in a `Response` object but I was not able to figure out how to evaluate 
additional properties in the schema object. I want to ensure the `mustExist` array are the only properties defined in the schema.

**Describe the solution you'd like**
I would like to know how to use `mustExist` in the custom rule to enforce a specific schema.

**Comment by adamaltman** [comment]
@jeremyfiel which are you looking for:

1. Enforce no additional properties in examples.

Schema
```
components:
  schemas:
    user:
       type: object
       properties:
          email:
              type: string
       additionalProperties: false
```
Example
```
"user": {
   "email": "adam@example.com",
   "foo": "bar
}
```

Problem: `Invalid example: additional properties are not allowed.`

2. A rule that evaluates the response schema properties to ensure it matches exactly the schema and not the examples. 

Schema
```
components:
  schemas:
    user:
       type: object
       properties:
          email:
              type: string
          phone:
              type: string
          secret:
              type: string
```

rule
```
...
mustExist:
  - email
  - phone
```

Problem:  `Response object must only have email and phone properties defined`

Or is it something else?
