### ISSUE TITLE
assertions error: values is not iterable.

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#645]
**Describe the bug**

```
Something went wrong when processing /Users/adam/Projects/Rebilly/api-definitions/openapi/openapi.yaml:

  - values is not iterable.

/Users/adam/.nvm/versions/node/v16.10.0/lib/node_modules/@redocly/openapi-cli/node_modules/@redocly/openapi-core/lib/rules/common/assertions/asserts.js:36
        for (let _val of values) {
                         ^
```

**To Reproduce**
1. Given this `.redocly.yaml` file
2. And this OpenAPI file(s)
3. Run this command with these arguments... `openapi ...`

**Expected behavior**

**Logs**
If applicable, add logs to help explain your problem.

**OpenAPI definition**

https://github.com/Rebilly/api-definitions/pull/836

**`openapi-cli` Version(s)**

1.0.0-beta.94

**`Node.js` Version(s)**

16.10.0

**Additional context**

Copied the example here: https://redocly.com/docs/cli/resources/rules/assertions/#examples

**Comment by adamaltman** [comment]
Further investigation reveals the issue is related to the info description pattern.

```yaml
    - subject: Info
      property: description
      message: Info description must be at least 30 characters and end with a full stop.
      severity: error
      defined: true
      minLength: 30
      # pattern: /\.$/
```

I believe this is because they are using a `$ref` for the info description field. However, it should not crash like this.
