### ISSUE TITLE
Adjust `assertions` syntax

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#647]
**Is your feature request related to a problem? Please describe.**

The assertions are not easy to share due to nested arrays.

**Describe the solution you'd like**

We would like to change the syntax from the **before**:

``` yaml
assertions:
  - AssertObject
  - AssertObject
```

To **desired change**:

```yaml
assert/user-supplied-name:
  AssertObject
assert/another-supplied-name:
  AssertObject
```

Here is a working sample:

```yaml
lint:
  rules:
    assert/tag-description-min-length-full-stop:
       subject: Tag
       property: description
       message: Tag description must be at least 30 characters and end with a full stop.
       severity: error
       defined: true
       minLength: 30
       pattern: /\.$/
```

The user supplied names **MUST** be unique.

The user rule must start with `assert/` to use the `AssertObject`.

**Describe alternatives you've considered**

Doing nothing.

**Additional context**

- Discussed in meeting today.
- Makes it easier to share rules.

**Comment by BohdanPetryshyn** [comment]
Hey @RomanHotsiy, could you please briefly describe the problem with nested arrays and assertions sharing?

**Comment by RomanHotsiy** [comment]
Yes.

Our current implementation is like this:

```yaml
lint:
  rules:
    some-rule: error
    assertions:
      - <AssertionObject1>
      - <AssertionObject2>
```

If someone finds some assertions online and wants to copy them they will most likely make a mistake: they will need not only to copy assertion object but also to enable a new assertions rule and put it there.

Another more important issue is that if I want to extend some existing config (that someone handcrafted using assertions) I can't do it. Because assertions is an array we don't have a good way to merge assertions. Right now we override.

Re nested arrays. This is common problem among our users. They struggle with deeply nested arrays in yaml and make mistakes with indentation.
