### ISSUE TITLE
The encoding object should map properties

### ISSUE THREAD

**Issue by adamaltman** [Redocly/openapi-cli#99]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#media-type-object

|encoding | Map[string, Encoding Object] | A map between a property name and its encoding information. The key, being the property name, MUST exist in the schema as a property. The encoding object SHALL only apply to requestBody objects when the media type is multipart or application/x-www-form-urlencoded.
-- | -- | --

However, I have an example where the encoding object is used properly and I receive an error complaining that the property's key is not allowed in that object.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#encoding-object-example

From my own example, it was defining the encoding for a property in the schema. 

```
The field 'file' is not allowed in OpenAPIEncoding. Use "x-" prefix or custom types to override this behavior.

Did you mean: style ?

Error was generated by no-extra-fields rule.
```

Here is a simplified version of that definition:

```yaml
required: true
content:
  multipart/form-data:
    schema:
      type: object
      required:
        - file
        - type
      properties:
          type: 
            type: string
            enum:
              - foo
          file:
            type: string
            format: binary
    encoding:
      file:
        contentType: image/gif, image/jpg, image/jpeg, image/png, image/bmp, image/tiff, application/pdf, image/heic
```
